service: bentoMergeInvoke

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:us-east-1:247910611346:function:simpleMerge-dev-simpleMerge"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:us-east-1:247910611346:*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:us-east-1:247910611346:table/Jobs/stream/*"

functions:
  mergeInvoke:
    handler: mergeInvoke/mergeInvoker.mergeInvoke
    timeout: 900
    #role: arn:aws:iam::247910611346:role/service-role/MergeInvokeLambdaRole
    environment:
      mergeLamdaArn: arn:aws:lambda:us-east-1:247910611346:function:simpleMerge-dev-simpleMerge
